name: gram
version: 0.1.0.0
synopsis: An all-purpose Telegram bot in Haskell
maintainer: Deniz Alp Durmaz <denizalpd@ogr.iu.edu.tr>
category: Web
license: BSD3
default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - LambdaCase
extra-source-files:
  - README.md

ghc-options:
  -Wall

dependencies:
  - base

executables:
  gram:
    main: Main.hs
    source-dirs:
      - src
    dependencies:
      - aeson
      - async
      - containers
      - directory
      - katip
      - load-env
      - optparse-applicative
      - privileged-concurrency
      - safe
      - text
      - tdlib-haskell-bindings
      - time
      - typed-duration
      - unix