resolver: lts-14.0

packages:
- .

extra-deps:
- typed-duration-0.1.1.0
- privileged-concurrency-0.7.0
- git: https://github.com/klappvisor/haskell-telegram-api.git
  commit: dcc491b6abee6157d4ec607c71ba3a4915eb0edb
- git: https://github.com/yigitozkavci/tdlib-haskell-bindings.git
  commit: e65157cabe366d0c21a4595b1bc50f49e9a4ff74
- fused-effects-lens-0.2.0.0

nix:
  enable: true
  packages: [glpk, pcre, curl, zlib, tdlib]
