name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix-path: nixpkgs=channel:nixos-unstable

    - name: lint
      run: |
        nix-shell
        ${scripts/ormolu_check.sh}
      
    - name: build
      run: nix-build